<a href="https://colab.research.google.com/github/prayasshrivastava/Python-Programming/blob/master/numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [10]:
import numpy as np
print("Enter rows and columns in terms of 'Pxq'")
rows,columns = input().split("x")  
rows=int(rows)
columns=int(columns)
array=np.random.rand(rows,columns)
np.savetxt('test1.txt', array, fmt='%d')
print(array)

Enter rows and columns in terms of 'Pxq'
3x4
[[0.07596236 0.84831895 0.47958764 0.85693398]
 [0.78616694 0.28207796 0.12618962 0.33892755]
 [0.70570288 0.73244973 0.15961093 0.46711062]]
